### PR TITLE
emit the data upon connect event

### PR DESCRIPTION
**Pull request by koox00**
It is very useful to have the socket id emitted as well.

### CODE REVIEW

**Comment by TheRusskiy** [comment]
@koox00 nice, thx, bumped the version and published

**Comment by koox00** [comment]
Sorry, the dev tools showed that it returned an object with `event` and `data` properties, but it seems it gets consumed somewhere so the response we get is only `{ socket_id: xxx.xxx}`.
I've made another PR GH-9

Also what is your workflow on developing this?

**Comment by TheRusskiy** [comment]
I probably need to make a set up in this repo itself so it can be tested. Right now I am testing changes in a separate project where this repo is used. Not the best way...

**Comment by koox00** [comment]
It would be much easier for someone else to contribute also ;)

**Pull request merged**
